### ISSUE TITLE
Not able to open weakauras

### ISSUE THREAD

**Issue by Damnedprinter** [mrbuds/WeakAuras2#2]
I downloaded the newest version 10mins prior to making this bug report.

When I log in to the beta stress test servers I get multiple errors:
`Message: Interface\AddOns\WeakAuras\Prototypes.lua:19: Cannot find a library instance of "SpellRange-1.0".
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\Prototypes.lua:19: Cannot find a library instance of "SpellRange-1.0".
[C]: in function `error'
Interface\AddOns\Clique\libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\WeakAuras\Prototypes.lua:19: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "SpellRange-1.0"."

Message: Interface\AddOns\WeakAuras\Types.lua:4: Cannot find a library instance of "LibSharedMedia-3.0".
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\Types.lua:4: Cannot find a library instance of "LibSharedMedia-3.0".
[C]: in function `error'
Interface\AddOns\Clique\libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\WeakAuras\Types.lua:4: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibSharedMedia-3.0"."

Message: Interface\AddOns\WeakAuras\WeakAuras.lua:34: Cannot find a library instance of "LibDBIcon-1.0".
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:34: Cannot find a library instance of "LibDBIcon-1.0".
[C]: in function `error'
Interface\AddOns\Clique\libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\WeakAuras\WeakAuras.lua:34: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibDBIcon-1.0"."

Message: Interface\AddOns\WeakAuras\Transmission.lua:219: bad argument #1 to 'pairs' (table expected, got nil)
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\Transmission.lua:219: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\WeakAuras\Transmission.lua:219: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

Message: Interface\AddOns\WeakAuras\BuffTrigger.lua:909: attempt to index field 'frames' (a nil value)
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\BuffTrigger.lua:909: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\BuffTrigger.lua:909: in main chunk

Locals: tinsert = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
next = <function> defined =[C]:-1
type = <function> defined =[C]:-1
BUFF_MAX_DISPLAY = 255
CombatLogGetCurrentEventInfo = <function> defined =[C]:-1
UnitGroupRolesAssigned = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:64
WeakAuras = <table> {
 table_to_string = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:9
 SetAuraVisibility = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:294
 doubleWidth = 2.500000
 RegisterRegionOptions = <function> defined @Interface\AddOns\WeakAuras\Init.lua:48
 BuildInfo = 11302
 buildTime = "Dev"
 prettyPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:26
 IsClassic = true
 PrintProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:263
 me = "Pacer"
 ScanAuras = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:416
 StartProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:54
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:60
 versionString = "Dev"
 ToggleProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:223
 newFeatureString = ""
 halfWidth = 0.625000
 PowerAurasSoundPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Sounds\"
 versionMismatchPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:30
 ProfileRenameAura = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:177
 printPrefix = "WeakAuras: "
 StopProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:206
 L = <table> {
 }
 GenerateUniqueID = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:100
 StartProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:182
 RegisterRegionType = <function> defined @Interface\AddOns\WeakAuras\Init.lua:45
 ScanAurasGroup = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:832
 normalWidth = 1.250000
 PowerAurasPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Auras\"
 StartProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:51
 maxTimerDuration = 604800
 aura_cache = <table> {
 }
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:57
}
L = <table> {
 Show Code = "Show Code"
}
BuffTrigger = <table> {
}
timer = nil
function_strings = nil
auras = nil
specificBosses = nil
specificUnits = nil
loaded_auras = nil
aura_cache = <table> {
 watched = <table> {
 }
 DAMAGER = 0
 playerRole = "NONE"
 GetDynamicInfo = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:156
 GetNumber = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:145
 Watch = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:125
 players = <table> {
 }
 TANK = 0
 AssertMemberList = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:274
 AssertMember = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:255
 max = 0
 Unwatch = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:137
 HEALER = 0
 DeassertMember = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:262
 DeassertAura = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:249
 AssertAura = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:219
 ForceUpdate = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:119
 GetPlayerDynamicInfo = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:175
 GetAffected = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:195
 GetUnaffected = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:208
 Rename = <function> d

Message: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1430: attempt to index field 'frames' (a nil value)
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1430: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\BuffTrigger2.lua:1430: in main chunk

Locals: tinsert = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
next = <function> defined =[C]:-1
type = <function> defined =[C]:-1
WeakAuras = <table> {
 table_to_string = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:9
 SetAuraVisibility = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:294
 doubleWidth = 2.500000
 RegisterRegionOptions = <function> defined @Interface\AddOns\WeakAuras\Init.lua:48
 BuildInfo = 11302
 buildTime = "Dev"
 prettyPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:26
 IsClassic = true
 PrintProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:263
 me = "Pacer"
 ScanAuras = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:416
 StartProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:54
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:60
 versionString = "Dev"
 ToggleProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:223
 newFeatureString = ""
 halfWidth = 0.625000
 PowerAurasSoundPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Sounds\"
 versionMismatchPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:30
 ProfileRenameAura = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:177
 printPrefix = "WeakAuras: "
 StopProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:206
 L = <table> {
 }
 GenerateUniqueID = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:100
 StartProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:182
 RegisterRegionType = <function> defined @Interface\AddOns\WeakAuras\Init.lua:45
 ScanAurasGroup = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:832
 normalWidth = 1.250000
 PowerAurasPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Auras\"
 StartProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:51
 maxTimerDuration = 604800
 aura_cache = <table> {
 }
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:57
}
L = <table> {
 Show Code = "Show Code"
}
timer = nil
BuffTrigger = <table> {
}
triggerInfos = <table> {
}
UnitGroupRolesAssigned = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:70
scanFuncName = <table> {
}
scanFuncSpellId = <table> {
}
scanFuncGeneral = <table> {
}
scanFuncNameGroup = <table> {
}
scanFuncSpellIdGroup = <table> {
}
scanFuncGeneralGroup = <table> {
}
unitExistScanFunc = <table> {
}
existingUnits = <table> {
}
groupScanFuncs = <table> {
}
groupCountScanFunc = <table> {
}
groupCount = <table> {
}
playerRole = <table> {
}
scanFuncNameMulti = <table> {
}
scanFuncSpellIdMulti = <table> {
}
cleanupTimerMulti = <table> {
}
matchData = <table> {
}
matchDataUpToDate = <table> {
}
matchDataMulti = <table> {
}
matchDataByTrigger = <table> {
}
matchDataChanged = <table> {
}
GetOrCreateSubTable = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:105
IsGroupTrigger = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:114
IsSingleMissing = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:118
HasMatchCount = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:122
ReferenceMatchData = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:130
ReferenceMatchDataMulti = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:140
MatchesTriggerInfoMulti = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:156
UpdateToolTipDataInMatchData = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:166
UpdateMatchData = <function> defined @Interface

Message: Interface\AddOns\WeakAuras\GenericTrigger.lua:777: attempt to index field 'frames' (a nil value)
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\GenericTrigger.lua:777: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\GenericTrigger.lua:777: in main chunk

Locals: tinsert = <function> defined =[C]:-1
tconcat = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
tostring = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
error = <function> defined =[C]:-1
setmetatable = <function> defined =[C]:-1
CombatLogGetCurrentEventInfo = <function> defined =[C]:-1
IsPlayerMoving = <function> defined =[C]:-1
aceEvents = <table> {
 UnregisterAllMessages = <function> defined @Interface\AddOns\MaxCam\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UnregisterAllEvents = <function> defined @Interface\AddOns\MaxCam\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SendMessage = <function> defined @Interface\AddOns\MaxCam\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 RegisterMessage = <function> defined @Interface\AddOns\MaxCam\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\MaxCam\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UnregisterEvent = <function> defined @Interface\AddOns\MaxCam\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 RegisterEvent = <function> defined @Interface\AddOns\MaxCam\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
}
WeakAuras = <table> {
 table_to_string = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:9
 SetAuraVisibility = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:294
 doubleWidth = 2.500000
 RegisterRegionOptions = <function> defined @Interface\AddOns\WeakAuras\Init.lua:48
 BuildInfo = 11302
 buildTime = "Dev"
 prettyPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:26
 IsClassic = true
 PrintProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:263
 me = "Pacer"
 ScanAuras = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:416
 StartProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:54
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:60
 versionString = "Dev"
 ToggleProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:223
 newFeatureString = ""
 ScanEventsInternal = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:665
 halfWidth = 0.625000
 PowerAurasSoundPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Sounds\"
 versionMismatchPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:30
 ActivateEvent = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:376
 ProfileRenameAura = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:177
 printPrefix = "WeakAuras: "
 StopProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:206
 L = <table> {
 }
 GenerateUniqueID = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:100
 ScanUnitEvents = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:638
 ScanEvents = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:608
 StartProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:182
 EndEvent = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:310
 RegisterRegionType = <function> defined @Interface\AddOns\WeakAuras\Init.lua:45
 split = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:92
 ScanAurasGroup = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:832
 normalWidth = 1.250000
 PowerAurasPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Auras\"
 StartProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:51
 maxTimerDuration = 604800
 aura_cache = <table> {
 }
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:57
}
L 

Message: Interface\AddOns\WeakAuras\AuraEnvironment.lua:58: Cannot find a library instance of "LibCustomGlow-1.0".
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\AuraEnvironment.lua:58: Cannot find a library instance of "LibCustomGlow-1.0".
[C]: in function `error'
Interface\AddOns\Clique\libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\WeakAuras\AuraEnvironment.lua:58: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibCustomGlow-1.0"."

Message: Interface\AddOns\WeakAuras\RegionTypes\AuraBar.lua:1: Cannot find a library instance of "LibSharedMedia-3.0".
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\AuraBar.lua:1: Cannot find a library instance of "LibSharedMedia-3.0".
[C]: in function `error'
Interface\AddOns\Clique\libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\WeakAuras\RegionTypes\AuraBar.lua:1: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibSharedMedia-3.0"."

Message: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:1: Cannot find a library instance of "LibSharedMedia-3.0".
Time: Thu May 23 14:06:47 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:1: Cannot find a library instance of "LibSharedMedia-3.0".
[C]: in function `error'
Interface\AddOns\Clique\libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:1: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibSharedMedia-3.0"."

Message: Error loading Interface\AddOns\WeakAuras\Libs\LibStub\LibStub.lua
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\AceConsole-3.0\AceConsole-3.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\AceConfig-3.0\AceConfig-3.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\AceTimer-3.0\AceTimer-3.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\AceSerializer-3.0\AceSerializer-3.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\AceEvent-3.0\AceEvent-3.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\lib.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\AceGUI-3.0-SharedMediaWidgets\widget.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Error loading Interface\AddOns\WeakAuras\Libs\LibCompress\LibCompress.lua
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Error loading Interface\AddOns\WeakAuras\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Error loading Interface\AddOns\WeakAuras\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Error loading Interface\AddOns\WeakAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Couldn't open Interface\AddOns\WeakAuras\Libs\LibCustomGlow-1.0\LibCustomGlow-1.0.xml
Time: Thu May 23 14:06:47 2019
Count: 4

Message: Error loading Interface\AddOns\WeakAuras\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua
Time: Thu May 23 14:06:47 2019
Count: 4

`

**Comment by Stanzilla** [comment]
Please download from here https://www.wowinterface.com/downloads/info24910-Classic-Beta1.html

**Comment by selfisch** [comment]
> Please download from here https://www.wowinterface.com/downloads/info24910-Classic-Beta1.html#other the one with classic in the name

Works, but why is it not possible to pull the latest from the git?
A download link in README.md would be fine if this is the only valid way.

**Comment by Stanzilla** [comment]
it is, you just have to take care about libs yourself
