### ISSUE TITLE
WA Lua error on login

### ISSUE THREAD

**Issue by azazuzulu** [mrbuds/WeakAuras2#3]
I will upload the files for the 10 error messages im getting.

They happen when you log into WOW Beta classic - on both alliance and horde - not that it should make any difference :)

I turned off all addons and only loaded WA - deleted any savedvariables for weakaura's too before going into the game.

Im using this link to download WA:  https://www.wowinterface.com/downloads/info24910-Classic-Beta1.html
[WA-error10.txt](https://github.com/mrbuds/WeakAuras2/files/3213194/WA-error10.txt)
[WA-error9.txt](https://github.com/mrbuds/WeakAuras2/files/3213195/WA-error9.txt)
[WA-error8.txt](https://github.com/mrbuds/WeakAuras2/files/3213196/WA-error8.txt)
[WA-error7.txt](https://github.com/mrbuds/WeakAuras2/files/3213197/WA-error7.txt)
[WA-error6.txt](https://github.com/mrbuds/WeakAuras2/files/3213198/WA-error6.txt)
[WA-error5.txt](https://github.com/mrbuds/WeakAuras2/files/3213199/WA-error5.txt)
[WA-error4.txt](https://github.com/mrbuds/WeakAuras2/files/3213200/WA-error4.txt)
[WA-error3.txt](https://github.com/mrbuds/WeakAuras2/files/3213201/WA-error3.txt)
[WA-error2txt.txt](https://github.com/mrbuds/WeakAuras2/files/3213202/WA-error2txt.txt)
[WA-error1.txt](https://github.com/mrbuds/WeakAuras2/files/3213203/WA-error1.txt)

**Comment by Stanzilla** [comment]
Oh I see, it's a problem with the layout of WoWinterface, try this https://www.wowinterface.com/downloads/getfile.php?id=24910&aid=102649

**Comment by azazuzulu** [comment]
Link was the fix thanks :)
