### ISSUE TITLE
Rogue CP trigger issue

### ISSUE THREAD

**Issue by PEmergence** [mrbuds/WeakAuras2#6]
**Describe the bug**
Making a text aura to show rogue combo points as a numeric value returns 3 as power type (energy) and always 0 as power value when the combo points trigger is selected.

**To Reproduce**
Make an aura triggered by;
Status
--Power
--Player
--Combo Points

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
## Version: @project-version@

**Was it working in a previous version? If yes, which was the last good one?**
N/A

Example Aura

!no1spQnmq4Fn9yLakQQQ3yPHT7QSjuSzPNmysMaUkyN12Hh7b(T3zSdp0EALICgpV(M5B8i6l4c2obRK(qrtRVwPbblFop9PSebRYO9m17GiR)abtQv7KELrto78sRNekBTbLl9NAWyDqHrx6eS4vTbtOhHrQ0FEVRuALB7N2FmIJ5vvoWlY6HXOCn1YtC4iAyQ5aypVI8)NNx9Lg6kD58Zblx1jyNUlfwydckpaIpKhhuxn1O0O4d5CE(lcwrRZB2rWmVPu6rxB7(lBrdyDxSqv63kyJW7O2cQtC3ZE33ROmkg1IYERAZgWsUNfMuDkcIrYWl9Tix4Axd7bCs1wvPokylhpIXxY4JMHUgS0rd3OtbRpwToyPfERvzHG5q7Ug1tvbJOqkeTCh4IL3vYtKneHTbQRFQSZgLSqGpCRGMAHqbXMMKMs5TRyKb6GI4wgXWkH1yhej9FNKoDY80qM1368aZq84EGhv(IPelNV2VhzPWuBSrcJ(geo)w4CiDgOypy1Y6xrQLiIS(FxW(hojvvNeS0KjiNDWylxyLnc2IRskClzSz3AZ5vCWfWsxQUmqP5OfjkCij9sckCBPyRXoH0gBj24zjjzxm09wACsgpzwCttWMyvVFE1FALLuAqK4bCQuBIyGehgAEZ9WQocLXNzzd6HpDRnYW2mrVf1sNlmrAGIW2EBTxDHhJwPxJk9MAScNL)48Kp4KJw))qK0qH4JSdBFD8Zp(2FHFeCvW(fSxW2J9)WbeBl()

**Comment by jec324** [comment]
/script print(GetComboPoints("player"," target"));   Always returns 0
